---
title: "Podstawowe metody klasyfikacji - Przemek Węglik"
date: "Semestr letni 2023/24"
output: html_document
---

## Ładowanie zbioru danych

```{r}
dataframe = read.csv("spotify-2023.csv")
names(dataframe)[names(dataframe) == "danceability_."] <- "danceability"
names(dataframe)[names(dataframe) == "valence_."] <- "valence"
names(dataframe)[names(dataframe) == "energy_."] <- "energy"
names(dataframe)[names(dataframe) == "acousticness_."] <- "acousticness"
names(dataframe)[names(dataframe) == "instrumentalness_."] <- "instrumentalness"
names(dataframe)[names(dataframe) == "liveness_."] <- "liveness"
names(dataframe)[names(dataframe) == "speechiness_."] <- "speechiness"

dataframe = transform(dataframe, streams = as.numeric(streams))

head(dataframe)
library(class)
library(MASS)
```

## Regresja logistyczna - multinomial

```{r}
library(nnet) 

model <- multinom(key ~ mode + danceability + valence + energy + acousticness, data = dataframe) 

summary(model)
```
```{r}
training_pred <- predict(model, dataframe, type="class")

accuracy <- mean(training_pred == dataframe$key)
accuracy
```

```{r}
library(caTools)
trainIndex <- sample.split(dataframe$key, SplitRatio = 0.8)
train <- subset(dataframe, trainIndex)
test <- subset(dataframe, !trainIndex)
```

Regresję wykonujemy na podstawie zbioru uczącego
```{r}
model2 <- multinom(key ~ mode + danceability + valence + energy + acousticness, data = train) 
summary(model2)
```
a otrzymany model wykorzystujemy do predykcji dla danych ze zbioru testowego
```{r logisticPredictionTrain}
testing_pred <- predict(model, test, type="class")

accuracy <- mean(testing_pred == test$key)
accuracy
```


### LDA

```{r}
model3 <- lda(key ~ mode + danceability + valence + energy + acousticness, data = train) 

model3
```


### QDA

```{r qda}
model4 <- qda(key ~ mode + danceability + valence + energy + acousticness, data = train) 

model4
```

## kNN


```{r}
train <- subset(dataframe, trainIndex)
test <- subset(dataframe, !trainIndex)
train = na.omit(train)[c("key", "danceability", "valence", "energy", "acousticness")]
test = na.omit(test)[c("key", "danceability", "valence", "energy", "acousticness")]

train_labels <- train$key
test_labels <- test$key

# Remove 'key' column from train and test
train$key <- NULL
test$key <- NULL

knn_result <- knn(train=train, test=test, cl=train_labels, k=3)

confusionMatrix <- table(pred=knn_result, true=test_labels)

accuracy <- sum(diag(confusionMatrix)) / sum(confusionMatrix)
print(accuracy)
```
